# Generated by Django 4.1.7 on 2023-04-02 04:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Level',
            },
        ),
        migrations.CreateModel(
            name='Organization_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Organization_address',
                'verbose_name_plural': 'Organization_address',
            },
        ),
        migrations.CreateModel(
            name='Organization_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Organization_name',
                'verbose_name_plural': 'Organization_name',
            },
        ),
        migrations.CreateModel(
            name='Student_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('place_of_birth', models.CharField(max_length=200)),
                ('user_parol', models.IntegerField()),
                ('user_login', models.CharField(max_length=60)),
                ('parents_name', models.CharField(max_length=100)),
                ('parents_phone_number', models.IntegerField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.level')),
                ('muassasa_manzili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.organization_address')),
                ('muassasa_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.organization_name')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('parent_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.group')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Studentlar',
            },
        ),
    ]
